yzharko/spbspu-labs-2024-tp

main.cpp
ponomarev.viacheslav/T0/main.cpp

А почему на часы именно эти 12 чисел попали?
это какой-то циферблат!?!?!?!??!?!?

ponomarev.viacheslav/T0

---

nikiforov.alexander/T0/main.cpp

nikiforov.alexander/T0

---

gorbunova.alena/T0/main.cpp

gorbunova.alena/T0

---

redko.arina/T0/main.cpp

redko.arina/T0

---

popov.nikita/T0/main.cpp

popov.nikita/T0

---

litsinger.ernest/T0/main.cpp

litsinger.ernest/T0

---

sadofeva.nastya/T0/main.cpp

sadofeva.nastya/T0

---

susidko.fedor/T0/main.cpp

susidko.fedor/T0

---

batunov.roman/T0/main.cpp

batunov.roman/T0

---

proselkov.stanislav/T0/main.cpp

Лабораторная работа T0. 
Проверка на адекватность.
Вывод фамилии и имени студента.

proselkov.stanislav/T0

---

hohlova.polina/T0/main.cpp

hohlova.polina/T0

---

zheleznyakov.mark/T0/main.cpp

Решение `T0`
---
We are SO back.

zheleznyakov.mark/T0

---

shagieva.dinara/T0/main.cpp

shagieva.dinara/T0

---

mihalchenko.vladislav/T0/main.cpp

mihalchenko.vladislav/T0

---

miheev.egor/T0/main.cpp

miheev.egor/T0

---

doroshenko.anna/T0/main.cpp

Лабораторная T0. Вывод фамилии и имени студента.
___________________________________________________________

doroshenko.anna/T0

---

reznikova.anna/P0/main.cpp
reznikova.anna/T0/main.cpp

лабораторная работа Т0
вывод фамилии и имени студента
------------------------------------------------------------------------------

reznikova.anna/T0

---

kovshikov.nikita/T0/main.cpp

T0 is T0 but T0 is not always T0

kovshikov.nikita/T0

---

sukacheva.maria/T0/main.cpp

Вывод имени и фамилии студента.

sukacheva.maria/T0

---

khomichenko.alisa/T0/main.cpp

khomichenko.alisa/T0

---

taskaev.matvei/T0/main.cpp

Лабораторная работа T0 
вывод фамилии и имени через точку
-------------------------------------------------------------------
В Политехе я не "БЕ" не "МЕ"
Но разбираюсь в аниме,
Я знаю много модных слов,
GitHub люблю сильней чем плов.

taskaev.matvei/T0

---

jirkov.vladimir/T0/main.cpp

jirkov.vladimir/T0

---

khoroshkin.maksim/T2/datastruct.cpp
khoroshkin.maksim/T2/datastruct.hpp
khoroshkin.maksim/T2/delimiter.hpp
khoroshkin.maksim/T2/main.cpp
khoroshkin.maksim/T2/scopeguard.cpp
khoroshkin.maksim/T2/scopeguard.hpp

Лабораторная работа T2. Алгоритмы I
• [DBL LIT] Вещественное поле с двойной точностью (double) в формате литерала:
:keyX 50.0d:
:keyX 50.0D:
• [ULL LIT] Беззнаковое максимально доступной ёмкости (unsigned long long) в формате литерала:
:keyX 89ull:
:keyX 89ULL:

khoroshkin.maksim/T2

---

taskaev.matvei/T2/datastruct.cpp
taskaev.matvei/T2/datastruct.hpp
taskaev.matvei/T2/delimeter.cpp
taskaev.matvei/T2/delimeter.hpp
taskaev.matvei/T2/iofmtguard.cpp
taskaev.matvei/T2/iofmtguard.hpp
taskaev.matvei/T2/main.cpp
taskaev.matvei/T2/structs.cpp
taskaev.matvei/T2/structs.hpp

**Лабораторная работа T2**
----------------------------------------------------------------------------------------------
`[ULL HEX]`
Беззнаковое максимально доступной ёмкости (unsigned long long) в формате шестнадцатиричного литерала:
:keyX 0xFFFA:
:keyX 0X0100f:
Цифры шестандцатиричного числа выводятся в верхнем регистре
`[CMP LSP] `
Комплексное число (std::complex< double >) в следующем виде:
:keyX #c(1.0 -1.0):
:keyX #c(-1.0 1.0):
Гарантируется, что вещественная и мнимая часть разделены ровно одним пробелом. При сравнении с другими полями должен быть использован модуль комплексного число

taskaev.matvei/T2

---

reznikova.anna/T2/DataStruct.cpp
reznikova.anna/T2/DataStruct.hpp
reznikova.anna/T2/Delimeter.cpp
reznikova.anna/T2/Delimeter.hpp
reznikova.anna/T2/Keys.cpp
reznikova.anna/T2/Keys.hpp
reznikova.anna/T2/ScopeGuard.cpp
reznikova.anna/T2/ScopeGuard.hpp
reznikova.anna/T2/main.cpp

**Лабораторная работа Алгоритмы I**
Варианты:
[ULL OCT] Беззнаковое максимально доступной ёмкости (unsigned long long) в формате восьмиричного литерала
[CMP LSP] Комплексное число (std::complex< double >)
----------------------------------------------------------------------------------------------------
как жаль что при написании лабы нельзя отыгрывать хаотично злого персонажа и приходится использовать CamelCase

reznikova.anna/T2

---

sobolevsky.misha/T2/dataStruct.cpp
sobolevsky.misha/T2/dataStruct.hpp
sobolevsky.misha/T2/helpStructs.cpp
sobolevsky.misha/T2/helpStructs.hpp
sobolevsky.misha/T2/main.cpp

ЛабaT2. Алгоритмы I
• [DBL LIT] Вещественное поле с двойной точностью (double) в формате литерала:
:keyX 50.0d:
:keyX 50.0D:
• [CHR LIT] Символ (char) в формате символьного литерала:
:keyX 'c':
:keyX 'A':

sobolevsky.misha/T2

---

kovshikov.nikita/T2/data_struct.cpp
kovshikov.nikita/T2/data_struct.hpp
kovshikov.nikita/T2/io_structures.cpp
kovshikov.nikita/T2/io_structures.hpp
kovshikov.nikita/T2/main.cpp
kovshikov.nikita/T2/scope_guard.cpp
kovshikov.nikita/T2/scope_guard.hpp

Варианты:
• [CHR LIT]
• [RAT LSP]

kovshikov.nikita/T2

---

popov.nikita/T2/dataStruct.cpp
popov.nikita/T2/dataStruct.hpp
popov.nikita/T2/delimeter.cpp
popov.nikita/T2/delimeter.hpp
popov.nikita/T2/iofmtguard.cpp
popov.nikita/T2/iofmtguard.hpp
popov.nikita/T2/main.cpp
popov.nikita/T2/structData.cpp
popov.nikita/T2/structData.hpp

Лабораторная работа T2 Алгоритмы
• [DBL SCI] Вещественное поле с двойной точностью (double) в научном формате:
:keyX 5.45e-2:
:keyX 5.45E-2:
• [ULL LIT] Беззнаковое максимально доступной ёмкости (unsigned long long) в формате литерала:
:keyX 89ull:
:keyX 89ULL:

popov.nikita/T2

---

redko.arina/T2/dataStruct.cpp
redko.arina/T2/structures.cpp
redko.arina/T3/commands.cpp
redko.arina/T3/commands.hpp
redko.arina/T3/main.cpp
redko.arina/T3/shape.cpp
redko.arina/T3/shape.hpp
redko.arina/T3/shapeFunctions.cpp
redko.arina/T3/shapeFunctions.hpp
redko.arina/common/delimiter.cpp
redko.arina/common/delimiter.hpp

`[RIGHTSHAPES] [INTERSECTIONS]`

redko.arina/T3

---

gorbunova.alena/T2/anotherStructs.hpp
gorbunova.alena/T2/dataStruct.cpp
gorbunova.alena/T2/dataStruct.hpp
gorbunova.alena/T2/delimiter.cpp
gorbunova.alena/T2/delimiter.hpp
gorbunova.alena/T2/iofmtguard.cpp
gorbunova.alena/T2/iofmtguard.hpp
gorbunova.alena/T2/main.cpp
gorbunova.alena/T2/yaDataStruct.cpp
gorbunova.alena/T2/yaDataStruct.hpp

• [CMP LSP] Комплексное число (std::complex< double >) в следующем виде:
:keyX #c(1.0 -1.0):
:keyX #c(-1.0 1.0):
• [RAT LSP] Рациональное число (std::pair< long long, unsigned long long >) в следующем
виде:
:keyX (:N -2:D 3:):
:keyX (:N 3:D 2:):

gorbunova.alena/T2

---

nikiforov.alexander/F0/commands.cpp
nikiforov.alexander/F0/commands.hpp
nikiforov.alexander/F0/main.cpp
nikiforov.alexander/F0/menu.cpp
nikiforov.alexander/F0/menu.hpp

`1.3.2. Частотный словарь. AVL`
Система команд:
1. help - вывод списка доступных команд с параметрами
2. create < filename > - создание частотного словаря из файла filename из папки с заданным названием
3. open < mkdir > - чтение всех добавленных частотных словарей из папки mkdir
4. delete < name > - удаление частотного словаря с названием name
5. list - вывод названий всех существующих частотных словарей
6. add < name1 > < name2 > - добавление частотного словаря name2 в словарь name1
7. unite < newname > < name1 > < name2 > - создание словаря newname объединением двух словарей name1 и name2
8. rename < name > < newname > - переименование словаря name на newname
9. clear < name1 > < name2 > - удаление всех слов из словаря name1 которые есть в словаре name2
10. save < mkdir > - сохранение …

nikiforov.alexander/F0

---

redko.arina/F0/HuffmanCode.cpp
redko.arina/F0/HuffmanCode.hpp
redko.arina/F0/main.cpp
redko.arina/F0/processingFunctions.cpp
redko.arina/F0/processingFunctions.hpp
redko.arina/F0/userCommands.cpp
redko.arina/F0/userCommands.hpp

1. help – вывод всех команд с пояснением.
2. code – кодирование текста, введенного пользователем.
3. code < filename > – кодирование текста файла.
4. decode – раскодирование текста, введенного пользователем.
5. decode < filename > – раскодирование текста файла.
6. recode < filename1 > < filename2 > – объединение файлов с кодировкой в один с новой кодировкой.
7. print – вывод результата на экран.
8. save < filename > – сохранение результата в файл.
9. quit – выход из режима работы с результатом.
10. compare < filename1 > < filename2 > – сравнение кодирования одинаковых символов в файлах.

redko.arina/F0

---

sukacheva.maria/F0/commands.cpp
sukacheva.maria/F0/commands.hpp
sukacheva.maria/F0/graph.cpp
sukacheva.maria/F0/graph.hpp
sukacheva.maria/F0/main.cpp
sukacheva.maria/F0/workspace.cpp
sukacheva.maria/F0/workspace.hpp

система команд
1. help – вывод всех доступных команд с параметрами
2. create < graph > < graphname > - создание пустого графа с названием  graphname
3. add < vertex > < name > – создание вершины графа с названием name
4. add < edge > < first_node, second_node, weight > - создание ребра между вершинами  first_node и second_node с весом weight; если  first_node == second_node или weight <= 0 обрабатывается ошибка
6. delete < vertex > < name > - удаление вершины name, если существуют ребра, ведущие к этой вершине, они также удаляются; если вершины name не существует, обрабатывается ошибка
7. delete < edge > < first_node, second_node > - удаление ребра между вершинами  first_node и second_node, если его не существует, то обрабатывается ошибка
8. capacity <  graphname > - вывод количества …

sukacheva.maria/F0

---

doroshenko.anna/F0/commands.cpp
doroshenko.anna/F0/commands.hpp
doroshenko.anna/F0/main.cpp

Тема 1.3.2. Частотный словарь. АВЛ
1) help - вывод списка доступных команд
2) create `<name>` - создание словаря с именем name
3) remove `<name>` - удаление словаря с именем name
4) print `<name>` - вывод содержимого словаря с именем name
5) sort `<frequency>` `<name>` - сортировка словаря по частоте
6) sort `<alphabet>` `<name>` - сортировка словаря по алфавиту
7) delete `<key>` - удаление элемента с ключом key
8) find `<key>` - вывод частоты слова с ключом key 
9) top `<name>` - вывод трех наиболее часто встречающихся слов словаря
10) open `<filename>` - открытие файла для создание из его содержимого словаря
11) write `<filename>` - открытие файла для записи словаря
12) stop - закрытие словаря для записи
13) save - завершение работы с файлом, выход из режима редактирования, сохранение …

doroshenko.anna/F0

---

reznikova.anna/F0/Commands.cpp
reznikova.anna/F0/Commands.hpp
reznikova.anna/F0/Graph.cpp
reznikova.anna/F0/Graph.hpp
reznikova.anna/F0/Vertex.cpp
reznikova.anna/F0/Vertex.hpp
reznikova.anna/F0/WorkSpace.cpp
reznikova.anna/F0/WorkSpace.hpp
reznikova.anna/F0/main.cpp

**Система команд:**
1. help – вывод всех доступных команд с параметрами
2. create < graph > < graphname > - создание пустого графа с названием  graphname
3. add < vertice > < index > – создание вершины графа с индексом index
4. add < edge > < first_vertice, second_vertice > - создание ребра между вершинами  first_vertice и second_vertice
6. delete < vertice > < name > - удаление вершины name, если существуют ребра, ведущие к этой вершине, они также удаляются; если вершины name не существует, обрабатывается ошибка
7. delete < edge > < first_vertice, second_vertice > - удаление ребра между вершинами  first_vertice и second_vertice, если его не существует, то обрабатывается ошибка
8. capacity <  graphname > - вывод количества вершин в графе graphname
9. adjacent < first_vertice, second_ …

reznikova.anna/F0

---

zhitnyj.dmitriy/F0/Commands.cpp
zhitnyj.dmitriy/F0/Commands.hpp
zhitnyj.dmitriy/F0/Graph.hpp
zhitnyj.dmitriy/F0/GraphUtils.cpp
zhitnyj.dmitriy/F0/GraphUtils.hpp
zhitnyj.dmitriy/F0/main.cpp

Вариант РГР: 2.2.2. Алгоритм поиска кратчайших путей для заданной вершины
Список команд:
```
help - Вывод команд с пояснением.
add v <вершина> - Добавляет вершину в граф.
add e <вершина1> <вершина2> <вес> - Добавляет ребро между двумя вершинами с указанным весом.
del v <вершина> - Удаляет вершину и все инцидентные ей ребра.
del e <вершина1> <вершина2> - Удаляет ребро между двумя вершинами.
dijkstra <вершина> - Находит кратчайшие пути от заданной вершины до всех других вершин, используя алгоритм Дейкстры.
path <вершина1> <вершина2> - Выводит кратчайший путь от заданной вершины до другой вершины после выполнения алгоритма поиска кратчайших путей.
show - Выводит текущее состояние графа.
save <файл> - Сохраняет текущее состояние графа в указанный файл.
load <файл> - Загружает состояние графа …
```

zhitnyj.dmitriy/F0

---

battsolmon.ankhbayar/T0/main.cpp
battsolmon.ankhbayar/T2/dataStruct.cpp
battsolmon.ankhbayar/T2/dataStruct.hpp
battsolmon.ankhbayar/T2/main.cpp

[ULL OCT] Беззнаковое максимально доступной ёмкости (unsigned long long) в формате воь-
смиричного литерала:
:keyX 076:
:keyX 01001:
[ULL HEX] Беззнаковое максимально доступной ёмкости (unsigned long long) в формате шест-
надцатиричного литерала:
:keyX 0xFFFA:
:keyX 0X0100f:

ankhbayar.battsolmon/T2

---

proselkov.stanislav/T2/DataStruct.cpp
proselkov.stanislav/T2/DataStruct.hpp
proselkov.stanislav/T2/main.cpp

Лабораторная работа Т2.
Варианты:  
SLL LIT
ULL LIT

proselkov.stanislav/T2

---

khomichenko.alisa/T2/dataStruct.cpp
khomichenko.alisa/T2/dataStruct.hpp
khomichenko.alisa/T2/helpers.cpp
khomichenko.alisa/T2/helpers.hpp
khomichenko.alisa/T2/main.cpp
khomichenko.alisa/T2/scopeGuard.cpp
khomichenko.alisa/T2/scopeGuard.hpp

[DBL SCI] Вещественное поле с двойной точностью (double) в научном формате
[SLL LIT] Знаковое максимально доступной ёмкости (long long) в формате литерала

khomichenko.alisa/T2

---

batunov.roman/T2/DataStruct.cpp
batunov.roman/T2/DataStruct.h
batunov.roman/T2/main.cpp

Лабораторная работа Т2.
Варианты DBL LIT и DBL SCI

batunov.roman/T2

---

khomichenko.alisa/T3/commands.cpp
khomichenko.alisa/T3/commands.hpp
khomichenko.alisa/T3/helpers.cpp
khomichenko.alisa/T3/helpers.hpp
khomichenko.alisa/T3/main.cpp
khomichenko.alisa/T3/polygon.cpp
khomichenko.alisa/T3/polygon.hpp

khomichenko.alisa/T3

---

khomichenko.alisa/F0/cmd.cpp
khomichenko.alisa/F0/cmd.hpp
khomichenko.alisa/F0/input.cpp
khomichenko.alisa/F0/input.hpp
khomichenko.alisa/F0/main.cpp
khomichenko.alisa/F0/utilities.cpp
khomichenko.alisa/F0/utilities.hpp

khomichenko.alisa/F0

---

panov.ilya/F0/commands.cpp
panov.ilya/F0/commands.hpp
panov.ilya/F0/dicts.hpp
panov.ilya/F0/main.cpp

1.1.2. Англо-русский словарь. AVL-дерево.
Система команд:
1. help - выводит все доступные команды.
2. create <name> - создание словаря с названием   name. Если словарь с таким именем уже существует, выводится сообщение   "Словарь с таким именем уже существует. Выберите другое имя." Если   имя не указано после команды, выводится сообщение "Необходимо указать   имя для создания словаря."
3 add   <word, name> - добавление слова в словарь с именем name. Если словарь с   указанным именем не существует, выводится сообщение "Словарь с таким   именем не существует." Если слово уже существует в словаре, выводится   сообщение "Слово уже существует в словаре."
4. change <key><name><translation>   - изменение значения элемента с ключом key в словаре name на translation   Если словаря с таким …

panov.ilya/F0

---

malanin.nikita/T3/Commands.cpp
malanin.nikita/T3/Commands.hpp
malanin.nikita/T3/Delimiters.cpp
malanin.nikita/T3/Delimiters.hpp
malanin.nikita/T3/Polygon.cpp
malanin.nikita/T3/Polygon.hpp
malanin.nikita/T3/StreamGuard.cpp
malanin.nikita/T3/StreamGuard.hpp
malanin.nikita/T3/main.cpp

malanin.nikita/T3

---

jirkov.vladimir/T2/main.cpp

jirkov.vladimir/T2

---

kaseev.andrey/F0/functions.cpp
kaseev.andrey/F0/functions.hpp
kaseev.andrey/F0/main.cpp

модернизированная S1
список команд:
help
multiply
sum
pop
change
clear
readfile
input
save

kaseev.andrey/F0

---

susidko.fedor/T2/DataStruct.cpp
susidko.fedor/T2/DataStruct.hpp
susidko.fedor/T2/DelAnd.cpp
susidko.fedor/T2/DelAnd.hpp
susidko.fedor/T2/main.cpp

Заполняет вектор данными и выводит отсортированным
Вариант:
SLL LIT
ULL BIN

susidko.fedor/T2
